# Generated by Django 5.2.8 on 2025-11-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectperdus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='object_images/'),
        ),
    ]
